name: Radminton Badminton Club
url: http://radminton.co.uk
description: Radminton is a friendly social badminton club who play every Thursday, 7-9pm at Brislington Enterprise College, Bristol
keywords: radminton, badminton, club, brislington, bristol
author: Liam Jay & Steve Lacey
markdown: redcarpet
permalink: pretty
pygments: true

favicon-sizes: [160x160, 96x96, 32x32, 16x16]
apple-touch-icon-sizes: [57x57, 114x114, 72x72, 144x144, 60x60, 120x120, 76x76, 152x152]
